travis:
  secure:
    BINSTAR_TOKEN: kRQxQVKBUHJtr3p4xRfrqrZX25rklhvp075Dm3CB2DOXuLtX6gjUkDvL0jJ55zfvAsZrsjdrY/FaJCm8waiJCSObpCFADgRGzGzL2rCD55EJ38fttTZz7q/Yu+91ddHe7+LJt2zUCWxJbw5uko7UKV69lX6XIh3guqTx1MfAwaG3FTk0PjaukxcA9PgKo/29mSU/tj6K8wExGv45f4DgFq85usTM08jBdiEN0ua75wgOZBNGZR2RwHuC6x79j7cubX4bMT7GF2ExseZMvhEk5aZGQuNepUYh9In8GU7SM1PeJ8ZHpo5Tp7Mu7cHtEeL7FsviFlP0qr5n4QWKl7imLT/MIVxkVySl5hI0shouNgV8QLEgAcpqQPm9FMIf9JZwQms2iS+RXqP7nmHpvzwauDLjCbGUMmTX1wY+5huA4ZVAsc2CydApSANDzTRe+zS4/WQxAU2RLvls3kQyuwBle1w0gmtXeHfNoVgkOC18P79iHiyUMHPQvePMxy1Qq7eWbK+GcLoYN4v+B1mc1qtGV/JykqJ/Va+PZCkhtt/KoSyfSLZAeFQPNxCNgLd9njqTE+HTLEZuG4Wd7CPsiaZj3d4iKc1hS7DhLeMg+S0lKRiE6u1hi/M8jA2x0wNMZdd4e2WxTzyzQQp/a9U10b3uyHTfnh+W1dnKqYqTRacipNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
