travis:
  secure:
    BINSTAR_TOKEN: ZyuoXWvz42UDfYdfFT+usBpxoFjtP7ePYX0o+Nl3Hp0TUQOoXQyBa3k5I4lwNmAta+YgPWxIFID//Nv3rHRVSJFcEKYL9FyWbwYn/7GNNDAnz5/NNTh4Ib2qTRk35F09dRi2XnjnY3b8RDNy5YIA89Fu2T2esW5jmkDFmSQjJahQJoLdjXR0XUIyZjsUegwSZlrqTH3a9XIOnFybZs2PwdZOqsUIZBh1XmWjaf3zx4Ci8h2jKr+yWahkFA3ZyF8moq3MrmsV6iki9c6Wy6p6NJvioaoaVZ1d5eOKPiptdiOMoDGwx1hqv742RXMfZk4JpURPs8hQhFmNDOVvU/IovKYSkVrLYB4HGo5D0WVMaQct3jw/34qsQzkbs5TC60zUhBdh0MzLAAM34O+ULb6wCqNrAbcQvH6JbKlmdwsGhK++higz8hvKlvKU7W1qUReGtWdFZ14mIrdIFgMv0NDcHq0V/sI+wAeCjQnjorK9NM35/m0Kdy7f1H1j9AvW/qaW3PbilIX4jsdwMx7bxCDM1KxpOc15KSaoLr8a1Gs98EXd7pricp/fH/TcRyrUdvA+XXXHwB7hfritsiNMnahCo8NvN/5GJ5os+A93jztOTxywNkTClRd9eqCCkmX6zOl5JnJByG5hKIQtL5/c7igSbgynQOzovhE0xI8+/XG0o3w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
